plugins:
  - '@dotcom-tool-kit/jest'
  - '@dotcom-tool-kit/circleci'
  - '@dotcom-tool-kit/npm'
  - '@dotcom-tool-kit/circleci-npm'
  - '@dotcom-tool-kit/eslint'
  - '@dotcom-tool-kit/prettier'
  - './toolkit/stylelint'
hooks: 
  test:local:
    - Eslint
    - Stylelint
    - JestLocal
  test:ci:
    - Eslint
    - Stylelint
    - JestCI
options:
  '@dotcom-tool-kit/eslint':
    files: '**/*.{js,yml,json}'
  '@dotcom-tool-kit/prettier':
    files: '**/*.{js,yml,json}'
